on: [push]
jobs:
  build-and-deploy:
    env:
      REGISTRY_URL: akskodeyacr.azurecr.io
      NAMESPACE: akskodey8190
      IMAGE_NAME: akskodey
      SECRET_NAME: akskodey

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/k8s-set-context@users/koushdey/setEnvVarSpike
      with:
         kubeconfig: ${{ secrets.aksKodey_7582a }} 
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep $NAMESPACE | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace $NAMESPACE`
        fi
       
    - uses: azure/k8s-deploy@users/jysin/ConfigFilePathsAddition
      with:
        namespace: ${{ env.NAMESPACE  }}
        manifests: |
          .devcontainer/manifests/deployment.yml
          .devcontainer/manifests/service.yml
          

        images: nginx
